### ISSUE TITLE
Product Order Change

### ISSUE THREAD

**Issue by kpierduta** [kpierduta/ecovend-website#102]
Can you change the order in the dropdown menu

RVM - 100
RVM - 200
RVM - 400
RVM - 1000
RVM - 2000

& on the page can the order be left to right
RVM 100, RVM 200, RVM 400, please

<img width="1096" alt="Screenshot 2021-02-15 at 19 41 06" src="https://user-images.githubusercontent.com/40568273/107987433-e2d85180-6fc5-11eb-98cc-624e8065e17a.png">
<img width="168" alt="Screenshot 2021-02-15 at 19 40 55" src="https://user-images.githubusercontent.com/40568273/107987437-e5d34200-6fc5-11eb-8168-c2d69aceb897.png">

**Comment by iamkunall** [comment]
@kpierduta please have a look https://www.eco-vend.co.uk/products is this is a right product order you want.
