### ISSUE TITLE
Table Data

### ISSUE THREAD

**Issue by kpierduta** [kpierduta/ecovend-website#103]
On the individual product pages, can these be set up so that if the field isn't filled in within Contentful, it doesn't show the row in the table at all?

<img width="830" alt="Screenshot 2021-02-16 at 10 16 17" src="https://user-images.githubusercontent.com/40568273/108049381-18ba1c00-7040-11eb-8cd9-89f33f5159b8.png">

<img width="808" alt="Screenshot 2021-02-16 at 10 17 33" src="https://user-images.githubusercontent.com/40568273/108049459-338c9080-7040-11eb-98b9-c5d7d0befc98.png">

**Comment by iamkunall** [comment]
@kpierduta please have a look https://www.eco-vend.co.uk/machine/rvm-2000 this is fixed now.
