### ISSUE TITLE
Website Changes (06/11/20)

### ISSUE THREAD

**Issue by kpierduta** [kpierduta/ecovend-website#93]
**Home page**
Add the paragraph of text below and contact button to the hero section 

Reverse vending machines swap recyclable materials such as plastic bottles and aluminium cans for special offer vouchers.

They're helping to save the environment and can even earn you advertising revenue from the media screens.

Perfect for shopping centres, small supermarkets, schools and more.

![ecovend-change](https://user-images.githubusercontent.com/40568273/98376393-510e8f00-203b-11eb-96eb-75dfe6de9023.png)

**Main Menu:**
Make the 'Contact' button stand out. Change into a button, matching style across the website (block orange with white text)
(as shown in screenshot below)

**Contact page:**
Change page title to 'Contact Us' 
Move contact form section up
Remove image on page

See screenshot

![new-contact-page-ecovend](https://user-images.githubusercontent.com/40568273/98379017-b617b400-203e-11eb-899f-2982b61c2849.png)

**Comment by kpierduta** [comment]
Hey @perminder-klair I had a chat with Ben, these are the only changes for right now, so no major updates planned from them at the moment :-) if you could fit this in next week that would be super, really great to chat earlier

**Comment by perminder-klair** [comment]
@kpierduta let us know if all good with changes
